# Generated by Django 3.2.25 on 2025-03-02 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类管理',
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlowerPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='节日名称')),
                ('date', models.DateField(blank=True, null=True, verbose_name='节日日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='节日描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '节日',
                'verbose_name_plural': '节日管理',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='RawProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('postText', models.CharField(max_length=255, null=True)),
                ('title_url', models.URLField(max_length=3000)),
                ('shop_url', models.URLField(max_length=3000)),
                ('img_url', models.URLField(max_length=1000)),
                ('style_1', models.CharField(blank=True, max_length=100, null=True)),
                ('style_2', models.CharField(blank=True, max_length=100, null=True)),
                ('style_3', models.CharField(blank=True, max_length=100, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('website_url', models.URLField(max_length=3000)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('post_free', models.BooleanField(default=0)),
                ('image_url', models.URLField(blank=True, max_length=255, null=True)),
                ('detail_url', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(related_name='categories', to='data_management.Category')),
                ('location', models.ManyToManyField(related_name='locations', to='data_management.FlowerLocation')),
                ('purpose', models.ManyToManyField(related_name='purposes', to='data_management.FlowerPurpose')),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='data_management.shop', verbose_name='店铺')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='data_management.datasource')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='优先级')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='data_management.category', verbose_name='分类')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='data_management.holiday', verbose_name='节日')),
            ],
            options={
                'verbose_name': '分类与节日关系',
                'verbose_name_plural': '分类与节日关系管理',
                'unique_together': {('category', 'holiday')},
            },
        ),
    ]
