# Generated by Django 3.2.25 on 2024-12-17 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='节日名称')),
                ('date', models.DateField(blank=True, null=True, verbose_name='节日日期')),
                ('description', models.TextField(blank=True, null=True, verbose_name='节日描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
            ],
            options={
                'verbose_name': '节日',
                'verbose_name_plural': '节日管理',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CategoryHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(blank=True, null=True, verbose_name='优先级')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='data_management.category', verbose_name='分类')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='data_management.holiday', verbose_name='节日')),
            ],
            options={
                'verbose_name': '分类与节日关系',
                'verbose_name_plural': '分类与节日关系管理',
                'unique_together': {('category', 'holiday')},
            },
        ),
    ]
