# Generated by Django 3.2.25 on 2025-03-02 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedproduct',
            name='deal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
