# Generated by Django 3.2.25 on 2024-12-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_categoryholiday_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(max_length=255)),
                ('shop', models.CharField(max_length=255)),
                ('is_post_free', models.BooleanField(default=False)),
                ('title_url', models.URLField()),
                ('shop_url', models.URLField()),
                ('img_url', models.URLField()),
                ('style_1', models.CharField(blank=True, max_length=100, null=True)),
                ('style_2', models.CharField(blank=True, max_length=100, null=True)),
                ('style_3', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='店铺名称')),
                ('website_url', models.URLField()),
                ('location', models.CharField(max_length=255)),
            ],
        ),
    ]
