# Generated by Django 3.2.25 on 2024-12-18 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_rawproducts_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawproducts',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
