# Generated by Django 3.2.25 on 2024-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0004_rawproducts_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawproducts',
            name='is_post_free',
        ),
        migrations.AddField(
            model_name='rawproducts',
            name='postText',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
