# Generated by Django 3.2.25 on 2024-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0005_auto_20241218_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawproducts',
            name='img_url',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='rawproducts',
            name='shop_url',
            field=models.URLField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='rawproducts',
            name='title_url',
            field=models.URLField(max_length=3000),
        ),
    ]
