# Generated by Django 3.2.25 on 2024-12-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0007_datasource_flowerlocation_flowerpurpose_normalizedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedproduct',
            name='category',
            field=models.ManyToManyField(related_name='categorys', to='data_management.Category'),
        ),
        migrations.AddField(
            model_name='normalizedproduct',
            name='post_free',
            field=models.BooleanField(default=0),
        ),
    ]
