# Generated by Django 3.2.25 on 2024-12-19 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0008_auto_20241219_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='normalizedproduct',
            old_name='locations',
            new_name='location',
        ),
    ]
