# Generated by Django 3.2.25 on 2024-12-20 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0009_rename_locations_normalizedproduct_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedproduct',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='data_management.shop', verbose_name='店铺'),
        ),
        migrations.AlterField(
            model_name='normalizedproduct',
            name='category',
            field=models.ManyToManyField(related_name='categories', to='data_management.Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='website_url',
            field=models.URLField(max_length=1000),
        ),
    ]
