# Generated by Django 3.2.25 on 2024-12-20 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0010_auto_20241220_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='website_url',
            field=models.URLField(max_length=3000),
        ),
    ]
