# Generated by Django 3.2.25 on 2024-12-20 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0011_alter_shop_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, verbose_name='店铺名称'),
        ),
    ]
