# Generated by Django 3.2.25 on 2024-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0012_alter_shop_name'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.UniqueConstraint(fields=('name', 'location'), name='unique_name_location'),
        ),
    ]
