# Generated by Django 3.2.25 on 2024-12-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0013_shop_unique_name_location'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='shop',
            name='unique_name_location',
        ),
    ]
