# Generated by Django 3.2.25 on 2024-12-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0014_remove_shop_unique_name_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedproduct',
            name='category',
            field=models.ManyToManyField(related_name='flowers', to='data_management.Category'),
        ),
    ]
