# Generated by Django 3.2.25 on 2024-12-29 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0015_alter_normalizedproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryholiday',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='data_management.category', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='categoryholiday',
            name='holiday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='data_management.holiday', verbose_name='节日'),
        ),
    ]
